### ISSUE TITLE
Redis auth

### ISSUE THREAD

**Issue by thetutlage** [AdamPflug/express-brute-redis#1]
Node-redis requires to call auth method in order to authenticate , how about doing same here

**Comment by AdamPflug** [comment]
You can pass your own redis instance with the `client` parameter. Alternatively you can access the created instance on at `.client` property of the store. I don't really want to worry about proxying too many commands. Either way you can access the auth method off of the underlying redis instance.

**Comment by thetutlage** [comment]
Make sense , realized later that i can simply pass password to the config object
